services:
  mysql:
    image: mikedhmount/gdsmysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gds37xx
      TZ: America/New_York
    ports:
      - "3307:3306"
    networks:
      - door-network
    restart: always
    volumes:
      - gds_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      retries: 10
      timeout: 5s
      start_period: 30s

  backend:
    image: mikedhmount/gdsbackend:latest
    container_name: backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gds37xx
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - door-network

  frontend:
    image: mikedhmount/gdsfrontend:latest
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - door-network
    environment:
      - NGINX_PORT=80
      - BACKEND_PORT=8080

networks:
  door-network:
    driver: bridge
volumes:
  gds_data:
